
import jsPDF from "jspdf";

export function generateTaxReportPDF(entries, year, logoBase64) {
  const doc = new jsPDF();

  const totalWin = entries
    .filter(e => e.result === "win")
    .reduce((sum, e) => sum + parseFloat(e.amount), 0);
  const totalLoss = entries
    .filter(e => e.result === "loss")
    .reduce((sum, e) => sum + parseFloat(e.amount), 0);
  const netTotal = totalWin - totalLoss;

  // Cover Page
  doc.addImage(logoBase64, "PNG", 70, 20, 70, 70);
  doc.setFontSize(18);
  doc.text("Gambling Activity Report", 105, 100, { align: "center" });
  doc.setFontSize(14);
  doc.text(`Tax Year: ${year}`, 105, 110, { align: "center" });
  doc.text("Generated by GambLogic", 105, 118, { align: "center" });

  // Entry Pages
  doc.addPage();
  doc.setFontSize(12);
  doc.text("Logbook Entries", 14, 20);

  let y = 30;
  entries.forEach((entry, idx) => {
    const lines = [
      `Date: ${entry.date}`,
      `Type: ${entry.type}`,
      `Category: ${entry.locationCategory}`,
      `Location: ${entry.specificLocation}`,
      `Amount: $${parseFloat(entry.amount).toFixed(2)}`,
      `Result: ${entry.result}`,
    ];

    lines.forEach(line => {
      doc.text(line, 14, y);
      y += 7;
    });

    y += 5;
    if (y > 270 && idx < entries.length - 1) {
      doc.addPage();
      y = 20;
    }
  });

  // Summary Page
  doc.addPage();
  doc.setFontSize(14);
  doc.text("Summary", 14, 20);

  doc.setFontSize(12);
  doc.text(`Total Winnings: $${totalWin.toFixed(2)}`, 14, 35);
  doc.text(`Total Losses: $${totalLoss.toFixed(2)}`, 14, 45);

  doc.setTextColor(netTotal >= 0 ? 0 : 255, netTotal >= 0 ? 128 : 0, 0);
  doc.text(`Net Total: $${netTotal.toFixed(2)}`, 14, 55);
  doc.setTextColor(0, 0, 0); // reset color

  doc.save(`Gambling_Report_${year}.pdf`);
}
